server.port = 9000
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

server.ssl.enabled=true

#keystore (backend cert + private key)
server.ssl.key-store=classpath:psp-mq.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=psp-mq

#truststore
server.ssl.trust-store=classpath:truststore.jks
server.ssl.trust-store-password=truststorepassword
server.ssl.trust-store-type=JKS