management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8093

spring:
  security:
    user:
      name: prometheus
      password: secret123

logging:
  file:
    name: F:\\Nevena\\faks\\master\\SEP\\projekat\\sep\\monitoring\\logs\\vivonet.log
