management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8093
  tracing:
    sampling:
      probability: 1.0

spring:
  security:
    user:
      name: prometheus
      password: secret123
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sep-realm
          jwk-set-uri: http://localhost:8080/realms/sep-realm/protocol/openid-connect/certs

keycloak:
  realm: sep-realm
  auth-server-url: http://localhost:8080
  resource: sep-vivonet-backend
  credentials:
    secret: Yg7DMUoa9UCZZjXEMLToWOyHzdj3Yjht

tracing:
  url: http://localhost:4318/v1/traces

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-N/A},%X{spanId:-N/A}]"
  file:
    name: F:\\Nevena\\faks\\master\\SEP\\projekat\\sep\\monitoring\\logs\\vivonet.log
