management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8093
  tracing:
    sampling:
      probability: 1.0

spring:
  security:
    user:
      name: prometheus
      password: secret123

tracing:
  url: http://localhost:4318/v1/traces

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-N/A},%X{spanId:-N/A}]"
  file:
    name: F:\\Nevena\\faks\\master\\SEP\\projekat\\sep\\monitoring\\logs\\vivonet.log
