spring.application.name=PSP
server.port=8090

server.ssl.enabled=true

#keystore (backend cert + private key)
server.ssl.key-store=classpath:psp.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=psp

#truststore
server.ssl.trust-store=classpath:truststore.jks
server.ssl.trust-store-password=truststorepassword
server.ssl.trust-store-type=JKS

spring.datasource.url=jdbc:postgresql://localhost:5432/psp
spring.datasource.username=postgres
spring.datasource.password=super

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


psp.app.jwtCookieName= psp
psp.app.jwtSecret= djanicgligorovsarac123123123123123123123123123123123123
psp.app.jwtExpirationMs= 90000000

spring.rabbitmq.address = localhost:5672