management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8090
  tracing:
    sampling:
      probability: 1.0

spring:
  security:
    user:
      name: prometheus
      password: secret123
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sep-realm
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/sep-realm/protocol/openid-connect/certs


keycloak:
  realm: sep-realm
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  resource: sep-psp-backend
  credentials:
    secret: wxjosAftVRKXRykM3AgEqnXSHvP1muI7

tracing:
  url: ${TRACING_URL:http://localhost:4318/v1/traces}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-N/A},%X{spanId:-N/A}]"
  file:
    name: F:\\Nevena\\faks\\master\\SEP\\projekat\\sep\\monitoring\\logs\\psp.log
