spring.application.name=PSP
server.port=8090

server.ssl.enabled=true

#keystore (backend cert + private key)
server.ssl.key-store=classpath:psp.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=psp

#truststore
server.ssl.trust-store=classpath:truststore.jks
server.ssl.trust-store-password=truststorepassword
server.ssl.trust-store-type=JKS

spring.datasource.url=jdbc:postgresql://localhost:5432/psp
spring.datasource.username=postgres
spring.datasource.password=super

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


psp.app.jwtCookieName= psp
psp.app.jwtSecret= djanicgligorovsarac123123123123123123123123123123123123
psp.app.jwtExpirationMs= 90000000
psp.app.jwtRefreshExpirationMs= 900000000

spring.rabbitmq.address = localhost:5672

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TODO some mail
spring.mail.password=TODO some pass
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.service-name=PSP
spring.cloud.consul.discovery.instance-id=PSP-8090
spring.cloud.consul.discovery.hostname=host.docker.internal
spring.cloud.consul.discovery.port=8090
spring.cloud.consul.discovery.health-check-url=https://host.docker.internal:8090/actuator/health
spring.cloud.consul.discovery.health-check-tls-skip-verify=true
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=3s

management.endpoints.web.exposure.include=health
management.health.mail.enabled=false