server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'VivoNet webshop'
    static_configs:
      - targets:
          - localhost
        labels:
          job: vivonet
          __path__: /logs/vivonet.log
  - job_name: 'PSP'
    static_configs:
      - targets:
          - localhost
        labels:
          job: psp
          __path__: /logs/psp.log
  - job_name: 'PCC'
    static_configs:
      - targets:
          - localhost
        labels:
          job: pcc
          __path__: /logs/pcc.log
  - job_name: 'Bank1'
    static_configs:
      - targets:
          - localhost
        labels:
          job: bank1
          __path__: /logs/bank1.log

  - job_name: 'Bank2'
    static_configs:
      - targets:
          - localhost
        labels:
          job: bank2
          __path__: /logs/bank2.log

  - job_name: 'EthPayment'
    static_configs:
      - targets:
          - localhost
        labels:
          job: bank2
          __path__: /logs/ethPayment.log