-- Tabela: Services
INSERT INTO Services (id, name, description, type_user, type_service) VALUES 
(1, 'Mobile Basic Plan', 'Basic mobile plan with limited calls and data.', 'PERSONAL', 'MOBILE'),
(2, 'Mobile Premium Plan', 'Premium mobile plan with unlimited calls and high-speed data.', 'PERSONAL', 'MOBILE'),
(3, 'Business Mobile Plan', 'Mobile plan designed for businesses with flexible data and call options.', 'BUSINESS', 'MOBILE'),
(4, 'Enterprise Mobile Plan', 'Comprehensive mobile solution for large enterprises, including shared data and calls.', 'BUSINESS', 'MOBILE'),
(5, 'Landline Basic Plan', 'Basic landline plan with limited local calls.', 'PERSONAL', 'LANDLINE'),
(6, 'Landline Premium Plan', 'Premium landline plan with unlimited local calls and national call discounts.', 'PERSONAL', 'LANDLINE'),
(7, 'Business Landline Plan', 'Landline plan for small businesses with flexible call packages.', 'BUSINESS', 'LANDLINE'),
(8, 'Enterprise Landline Plan', 'Comprehensive landline solution for large enterprises with shared minutes.', 'BUSINESS', 'LANDLINE'),
(9, 'Home Basic Internet Plan', 'Basic internet plan for home use with moderate speed and data.', 'PERSONAL', 'INTERNET'),
(10, 'Premium Home Internet Plan', 'High-speed internet for home use with large data allowance.', 'PERSONAL', 'INTERNET'),
(11, 'Basic TV Package', 'Basic TV package with a selection of local and international channels.', 'PERSONAL', 'TV'),
(12, 'Home Entertainment TV', 'Entertainment-focused TV package with additional features like DVR and HD channels.', 'PERSONAL', 'TV'),
(13, 'Business TV Package', 'Business TV solution with a focus on news and business-related channels.', 'BUSINESS', 'TV'),
(14, 'Enterprise TV Solution', 'Enterprise-level TV package with premium channels and shared access.', 'BUSINESS', 'TV'),
(15, 'Business Internet Basic', 'Basic internet plan for small businesses.', 'BUSINESS', 'INTERNET'),
(16, 'Enterprise Internet Plan', 'High-speed internet solution for large enterprises.', 'BUSINESS', 'INTERNET');

-- Tabela: TariffPlans
INSERT INTO tariff_plan (id, service_id, name, description, price, duration_contract, internet_gb, number_minute, numbersms, number_channel, hd_channel, speed_internet_mbps) VALUES
(1, 1, 'Basic Data Plan', 'Provides 2GB of data and 100 minutes of calls.', 10, 12, 2, 100, NULL, NULL, NULL, NULL),
(2, 1, 'Advanced Data Plan', 'Provides 5GB of data, 300 minutes of calls, and 100 SMS.', 20, 12, 5, 300, 100, NULL, NULL, NULL),
(3, 2, 'Unlimited Plan', 'Unlimited calls and 10GB of high-speed data.', 40, 24, 10, -1, NULL, NULL, NULL, NULL),
(4, 2, 'Super Plan', 'Unlimited calls, 15GB of data, and 500 SMS.', 50, 24, 15, -1, 500, NULL, NULL, NULL),
(5, 3, 'Business Starter Plan', '5GB of data, 500 minutes of calls, and 500 SMS for businesses.', 30, 12, 5, 500, 500, NULL, NULL, NULL),
(6, 3, 'Business Unlimited Plan', 'Unlimited calls and 20GB of data with priority customer support.', 75, 24, 20, -1, 1000, NULL, NULL, NULL),
(7, 4, 'Enterprise Plan 50GB', '50GB of shared data, unlimited calls, and 5000 SMS for employees.', 150, 24, 50, -1, 5000, NULL, NULL, NULL),
(8, 4, 'Enterprise Premium Plan', 'Unlimited calls, 100GB of shared data, and 10,000 SMS for large enterprises.', 250, 36, 100, -1, 10000, NULL, NULL, NULL),
(10, 5, 'Basic Call Plan', 'Includes 100 local minutes per month.', 15, 12, NULL, 100, NULL, NULL, NULL, NULL),
(11, 5, 'Extended Call Plan', 'Includes 300 local minutes and 50 national minutes.', 25, 12, NULL, 350, NULL, NULL, NULL, NULL),
(12, 6, 'Unlimited Local Plan', 'Unlimited local calls and 100 national minutes.', 35, 24, NULL, -1, NULL, NULL, NULL, NULL),
(13, 6, 'National Plus Plan', 'Unlimited local calls, 300 national minutes.', 50, 24, NULL, -1, NULL, NULL, NULL, NULL),
(14, 7, 'Business Starter Plan', '200 local minutes and 100 national minutes for small businesses.', 40, 12, NULL, 300, NULL, NULL, NULL, NULL),
(15, 7, 'Business Unlimited Plan', 'Unlimited local and national calls with priority support.', 80, 24, NULL, -1, NULL, NULL, NULL, NULL),
(18, 9, 'Basic Internet Plan', 'Provides 50GB of data and 10 Mbps speed.', 25, 12, 50, NULL, NULL, NULL, NULL, 10),
(19, 9, 'Standard Internet Plan', 'Provides 100GB of data and 30 Mbps speed.', 40, 12, 100, NULL, NULL, NULL, NULL, 30),
(20, 10, 'High-Speed Internet Plan', 'Unlimited data and 100 Mbps speed.', 60, 24, -1, NULL, NULL, NULL, NULL, 100),
(21, 10, 'Ultra-Speed Internet Plan', 'Unlimited data and 1Gbps speed.', 150, 36, -1, NULL, NULL, NULL, NULL, 1000),
(22, 11, 'Standard TV Plan', 'Provides 50 channels, including local channels and some international ones.', 20, 12, NULL, NULL, NULL, 50, FALSE, NULL),
(23, 11, 'Premium TV Plan', 'Provides 100 channels, including HD channels and sports channels.', 40, 12, NULL, NULL, NULL, 100, TRUE, NULL),
(24, 12, 'Entertainment TV Plan', 'Provides 150 channels including HD and some premium movie channels.', 60, 24, NULL, NULL, NULL, 150, TRUE, NULL),
(25, 12, 'Ultimate Entertainment TV Plan', 'Provides 200 channels, including all HD channels, premium channels, and sports.', 100, 36, NULL, NULL, NULL, 200, TRUE, NULL),
(26, 13, 'Business Starter TV Plan', 'Provides 50 channels tailored to business professionals.', 40, 12, NULL, NULL, NULL, 50, FALSE, NULL),
(27, 13, 'Business Premium TV Plan', 'Provides 100 channels including news, business, and international channels.', 80, 24, NULL, NULL, NULL, 100, TRUE, NULL),
(28, 14, 'Enterprise Starter TV Plan', '100 channels with essential business content.', 120, 12, NULL, NULL, NULL, 100, FALSE, NULL),
(29, 14, 'Enterprise Premium TV Plan', '200 channels including HD and international channels.', 200, 24, NULL, NULL, NULL, 200, TRUE, NULL),
(30, 15, 'Business Standard Plan', '50GB of data with 20 Mbps speed.', 50, 12, 50, NULL, NULL, NULL, NULL, 20),
(31, 15, 'Business Unlimited Plan', 'Unlimited data with 50 Mbps speed.', 100, 24, -1, NULL, NULL, NULL, NULL, 50),
(32, 16, 'Enterprise High-Speed Plan', 'Unlimited data with 100 Mbps speed.', 200, 24, -1, NULL, NULL, NULL, NULL, 100),
(33, 16, 'Enterprise Ultra-Speed Plan', 'Unlimited data with 1 Gbps speed.', 500, 36, -1, NULL, NULL, NULL, NULL, 1000),
(34, 8, 'Enterprise Landline Basic Plan', 'Includes 500 local minutes and 100 national minutes.', 100, 12, NULL, 600, NULL, NULL, NULL, NULL),
(35, 8, 'Enterprise Landline Premium Plan', 'Unlimited local and national calls with priority customer support.', 200, 24, NULL, -1, NULL, NULL, NULL, NULL);
